version: '2'
volumes:
 dbdata:

services:
 mysql:
  image: mysql:5.7
  container_name: mysql
  volumes:
    - dbdata:/var/lib/mysql
    - ./schema:/docker-entrypoint-initdb.d
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=2DV514
    - MYSQL_USER=root
    - MYSQL_PASSWORD=secret
  ports:
    - "3306:3306"